language: c++
env:
  - DEBUG=1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - catch
script:
  - mkdir build; cd build; cmake ../; make; make Test

